version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    volumes:
      - keycloak_data:/opt/keycloak/data

  db-usuarios:
    image: postgres:15-alpine
    container_name: db_usuarios
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_usuarios
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_usuarios:/var/lib/postgresql/data

  ms-usuarios:
    build: .
    container_name: ms-usuarios
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-usuarios:5432/db_usuarios
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      #- SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/tpi-backend
    depends_on:
      - db-usuarios
      - keycloak

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db-usuarios

volumes:
  keycloak_data:
  postgres_data_usuarios:
  pgadmin_data: